name: Build Acer

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Set mod version
      run: yq -p=props -o=props ".modVersion = \"$GITHUB_REF_NAME\"" -i gradle.properties

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: ./gradlew build

    - name: Build changelog
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file: "false"
        skip-commit: "true"
        skip-git-pull: "true"

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/libs/*.jar"
        tag: ${{ steps.changelog.outputs.tag }}
        name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}

  deploy:
    runs-on: ubuntu-22.04
    environment: maple
    env:
      FILE: "acer-${{ github.ref_name }}.jar"
    steps:
      - name: Download JAR
        uses: robinraju/release-downloader@v1
        with:
          tag: $GITHUB_REF_NAME
          fileName: "$FILE"

      - name: Upload
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          sftp -oPort=$SFTP_PORT -oStrictHostKeyChecking=no -b - $SFTP_USERNAME@$SFTP_HOST <<EOF
            rm mods/acer-*.jar
            put $FILE mods/
          EOF
